export const company_type_options = [
    { label: 'Private Limited', value: 'Private Limited' },
    { label: 'Public Limited', value: 'Public Limited' },
    { label: 'Limited liability partnership (LLP)', value: 'Limited liability partnership (LLP)' },
    { label: 'Partnership', value: 'Partnership' },
    { label: 'Proprietorship', value: 'Proprietorship' },
    { label: 'Government', value: 'Government' },
    { label: 'One Person Company', value: 'One Person Company' },
];

export const company_age_options = [
    { label: 'Less Than 1 Year', value: 'Less than 1 Year' },
    { label: '1-3 Year', value: '1-3 Year' },
    { label: 'Above 3 Years', value: 'Above 3 Years' }
];

export const typeOfBusinessOptions = [
    { label: 'Manufacturing', value: 'Manufacturing' },
    { label: 'Trading', value: 'Trading' },
    { label: 'Service', value: 'Service' },
    { label: 'Retailer', value: 'Retailer' }
];

export const turnoverOptions = [
    { label: '0-25K', value: '0-25K' },
    { label: '25K-1 Lac', value: '25K-1 Lac' },
    { label: '1-5 Lacs', value: '1-5 Lacs' },
    { label: '5-25 Lacs', value: '5-25 Lacs' },
    { label: '25 Lacs+', value: '25 Lacs+' }
];

export const gstOptions = [
    { label: 'Yes', value: 'Yes' },
    { label: 'No', value: 'No' },
]

export const categoryOptions = [
    { label: "Category", value: "" },
    { label: "Advisory services (legal, business, educational, psychological etc.)", value: "Advisory services (legal, business, educational, psychological etc.)" },
    { label: "Aircel distributor / R-com distributor", value: "Aircel distributor / R-com distributor" },
    { label: "Apparel, Readymade garments", value: "Apparel, Readymade garments" },
    { label: "Arms and ammunition dealers", value: "Arms and ammunition dealers" },
    { label: "Arts, design and other creative services", value: "Arts, design and other creative services" },
    { label: "Automobile accessories / service centre", value: "Automobile accessories / service centre" },
    { label: "Automotive parts", value: "Automotive parts" },
    { label: "BPO/KPO & facility management", value: "BPO/KPO & facility management" },
    { label: "Bar / Liquor", value: "Bar / Liquor" },
    { label: "CSC, photocopying and other documents and ID (Aadhar, PAN) related services, Kisan seva kendra", value: "CSC, photocopying and other documents and ID (Aadhar, PAN) related services, Kisan seva kendra" },
    { label: "Cab Services", value: "Cab Services" },
    { label: "Camera, CCTV and related accessories", value: "Camera, CCTV and related accessories" },
    { label: "Cargo and retail transport service", value: "Cargo and retail transport service" },
    { label: "Chain restaurant / verified income", value: "Chain restaurant / verified income" },
    { label: "Chemist, Retail health accessories, medicines and supplements", value: "Chemist, Retail health accessories, medicines and supplements" },
    { label: "Clinics, hospital,nursing home, lab, gym, pet clinic etc.", value: "Clinics, hospital,nursing home, lab, gym, pet clinic etc." },
    { label: "Computer, Mobile and related accessories", value: "Computer, Mobile and related accessories" },
    { label: "Computer, mobile and camera repairing service", value: "Computer, mobile and camera repairing service" },
    { label: "Construction equipment including building, road, sewage etc.", value: "Construction equipment including building, road, sewage etc." },
    { label: "Construction material like cement, bricks, sand etc", value: "Construction material like cement, bricks, sand etc" },
    { label: "Corporate services / Corporate bookings", value: "Corporate services / Corporate bookings" },
    { label: "Cotton bales, Textile manufacturing", value: "Cotton bales, Textile manufacturing" },
    { label: "Countdown Timers, Electronic Scoreboards and Digital Clocks", value: "Countdown Timers, Electronic Scoreboards and Digital Clocks" },
    { label: "Courier,  \"Design, Fabrication & Painting Services\"", value: "Courier,  \"Design, Fabrication & Painting Services\"" },
    { label: "Distributor of cooking/commercial Gas", value: "Distributor of cooking/commercial Gas" },
    { label: "Eco-friendly solutions for industry (solar, greenhouse, biomass, recycling, etc.)", value: "Eco-friendly solutions for industry (solar, greenhouse, biomass, recycling, etc.)" },
    { label: "Edible Oil business", value: "Edible Oil business" },
    { label: "Educational Institute (Pre-school, school, college, coaching center, library etc.)", value: "Educational Institute (Pre-school, school, college, coaching center, library etc.)" },
    { label: "Educational products (books, educational toys, stationeries, e-learning etc.)", value: "Educational products (books, educational toys, stationeries, e-learning etc.)" },
    { label: "Electronic sensors, devices", value: "Electronic sensors, devices" },
    { label: "Entertainment Event", value: "Entertainment Event" },
    { label: "Equipment used in agriculture", value: "Equipment used in agriculture" },
    { label: "Event Management", value: "Event Management" },
    { label: "Fabric (woven and non-woven) & textiles", value: "Fabric (woven and non-woven) & textiles" },
    { label: "Facility Management Services", value: "Facility Management Services" },
    { label: "Fibres, threads, buttons and other raw materials supplier to textile industry", value: "Fibres, threads, buttons and other raw materials supplier to textile industry" },
    { label: "Film Producer", value: "Film Producer" },
    { label: "Financial service providers (Chit funds/ small finance companies/Stock broking Companies)", value: "Financial service providers (Chit funds/ small finance companies/Stock broking Companies)" },
    { label: "Financial service providers (DSA,agents and other intermediators)", value: "Financial service providers (DSA,agents and other intermediators)" },
    { label: "Financial service providers (NBFCs/ Other money lending companies)", value: "Financial service providers (NBFCs/ Other money lending companies)" },
    { label: "Fire fighting equipment, safety materials", value: "Fire fighting equipment, safety materials" },
    { label: "Footwear, bags, cosmetics and other fashion accessories", value: "Footwear, bags, cosmetics and other fashion accessories" },
    { label: "Freight forwarding services", value: "Freight forwarding services" },
    { label: "Furniture & Fixtures (including on rent)", value: "Furniture & Fixtures (including on rent)" },
    { label: "Grocery/ Kirana store / Departmental Store", value: "Grocery/ Kirana store / Departmental Store" },
    { label: "Hardware & Fittings (ceramics, tiles, cables, lights etc.)", value: "Hardware & Fittings (ceramics, tiles, cables, lights etc.)" },
    { label: "Hardware provider to telecom industry", value: "Hardware provider to telecom industry" },
    { label: "Heavy machineries & Robotics", value: "Heavy machineries & Robotics" },
    { label: "Home & Kitchen Appliances", value: "Home & Kitchen Appliances" },
    { label: "Home Decor, interior items, kitchen accessories, toys, gift articles", value: "Home Decor, interior items, kitchen accessories, toys, gift articles" },
    { label: "Hotels, resorts and club", value: "Hotels, resorts and club" },
    { label: "Housekeeping products", value: "Housekeeping products" },
    { label: "Housekeeping, security & industrial labour supply", value: "Housekeeping, security & industrial labour supply" },
    { label: "Imitation jewellery", value: "Imitation jewellery" },
    { label: "Industrial and customized software, applications and ITES", value: "Industrial and customized software, applications and ITES" },
    { label: "Installation and repair services for telecom products", value: "Installation and repair services for telecom products" },
    { label: "Intelligence Agencies/ Private Security Firms", value: "Intelligence Agencies/ Private Security Firms" },
    { label: "Interior Designers", value: "Interior Designers" },
    { label: "Jewellery, precious metals and stones", value: "Jewellery, precious metals and stones" },
    { label: "Law services, astrological services, etc.", value: "Law services, astrological services, etc." },
    { label: "Leather Trading,  \"Live Stock Trading\"", value: "Leather Trading,  \"Live Stock Trading\"" },
    { label: "Material handling service provider", value: "Material handling service provider" },
    { label: "Medical, non-medical & wellness equipments", value: "Medical, non-medical & wellness equipments" },
    { label: "Mining & Mining Products", value: "Mining & Mining Products" },
    { label: "Mobile and related accessories", value: "Mobile and related accessories" },
    { label: "Mobile recharge, Telecom, DTH, data service provider (telephone, internet,broadband, ISP, leased line etc.)", value: "Mobile recharge, Telecom, DTH, data service provider (telephone, internet,broadband, ISP, leased line etc.)" },
    { label: "Musical Instruments, bulbs, tubelights", value: "Musical Instruments, bulbs, tubelights" },
    { label: "Networking, storage, data management and other support services", value: "Networking, storage, data management and other support services" },
    { label: "Non-metal products like wood, paper, plastic, glass, etc", value: "Non-metal products like wood, paper, plastic, glass, etc" },
    { label: "Oils, Paint, Chemicals and petroleum products", value: "Oils, Paint, Chemicals and petroleum products" },
    { label: "Other metals, alloys, minerals and their scraps", value: "Other metals, alloys, minerals and their scraps" },
    { label: "Others", value: "Others" },
    { label: "Outdoor furniture (swings etc.)", value: "Outdoor furniture (swings etc.)" },
    { label: "Outsourced consultancy (recruitment, research, placement, transcription, visa etc.)", value: "Outsourced consultancy (recruitment, research, placement, transcription, visa etc.)" },
    { label: "Pet Shop, Pet Clinic & Pet Grooming Parlour", value: "Pet Shop, Pet Clinic & Pet Grooming Parlour" },
    { label: "Petrol pump & Gas station,  \"Power\"", value: "Petrol pump & Gas station,  \"Power\"" },
    { label: "Professional services (branding, media, architecture, saloon, beauty parlour etc.)", value: "Professional services (branding, media, architecture, saloon, beauty parlour etc.)" },
    { label: "Property dealing & management (Rent, lease or Sell)", value: "Property dealing & management (Rent, lease or Sell)" },
    { label: "Raw materials and parts used for manufacturing", value: "Raw materials and parts used for manufacturing" },
    { label: "Real estate developer, Civil contractor", value: "Real estate developer, Civil contractor" },
    { label: "Renewal (other than Via)", value: "Renewal (other than Via)" },
    { label: "Repair and maintenance services", value: "Repair and maintenance services" },
    { label: "Repair and servicing of household appliances", value: "Repair and servicing of household appliances" },
    { label: "Restaurants, Cafes, food outlets & catering", value: "Restaurants, Cafes, food outlets & catering" },
    { label: "Retail and standard softwares, applications and ITES", value: "Retail and standard softwares, applications and ITES" },
    { label: "Seeds, Fertilizer, Pesticides, Cattle feeds and agricultural products", value: "Seeds, Fertilizer, Pesticides, Cattle feeds and agricultural products" },
    { label: "Shares/Bitcoins/Old coins trading or Other speculative activities", value: "Shares/Bitcoins/Old coins trading or Other speculative activities" },
    { label: "Shipping Services", value: "Shipping Services" },
    { label: "Supplier for switches,cables etc", value: "Supplier for switches,cables etc" },
    { label: "Support services (facilitators, intermediators, agents, etc.)", value: "Support services (facilitators, intermediators, agents, etc.)" },
    { label: "Support services to industries like industrial design, warehousing, testing, repairing etc.", value: "Support services to industries like industrial design, warehousing, testing, repairing etc." },
    { label: "Tax planners / Auditors", value: "Tax planners / Auditors" },
    { label: "Tea / coffee vending machine & Tea / Coffee powder to Government / corporates", value: "Tea / coffee vending machine & Tea / Coffee powder to Government / corporates" },
    { label: "Ticket, Travel & Tour Packages", value: "Ticket, Travel & Tour Packages" },
    { label: "Tobacco Products", value: "Tobacco Products" },
    { label: "Tools and equipments including electricals,transformers, inverters and batteries", value: "Tools and equipments including electricals,transformers, inverters and batteries" },
    { label: "Vegetables, Fruits, Milk and other dairy products, Spices, Sea-food and food-processing", value: "Vegetables, Fruits, Milk and other dairy products, Spices, Sea-food and food-processing" },
    { label: "Vehicles (New/second hand)", value: "Vehicles (New/second hand)" }
];

